// This file is automatically generated. DO NOT EDIT.

class AppConstants {
  static const String app_name = 'BaiExpress Seller';
  static const String packageName = 'com.baiexpress.seller';
  static const String iosPackage = 'com.baiexpress.seller';
  static const String title = 'eShop Multi-Vendor - Seller';
  //please add your panel's API base URL here (you can find from settings->client APIs)
  // static const String baseUrl =
  //     'https://vendor.eshopweb.store/seller/app/v1/api/'; // demo
  // static const String chatBaseUrl =
  //     'https://vendor.eshopweb.store/seller/app/v1/Chat_Api/'; //demo
  static const String baseUrl =
      'https://baiexpress.com/seller/app/v1/api/'; //dev
  static const String chatBaseUrl =
      'https://baiexpress.com/seller/app/v1/Chat_Api/'; //dev
  static const String defaultLanguage = 'en';
}
